# This pipeline run three stages Test, Build and Deploy
stages:
  - build
  - deploy

# Open variables for S3
# AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are protected variables
# added in the gitlab interface : Project | Settings | CI / CD | Variables
variables:
  AWS_DEFAULT_REGION: eu-west-3 # The region of our S3 bucket
  BUCKET_NAME: publication-goffinet  # gitbook-gitlab.aws-fr.com Your bucket name

# the 'pdf' job will build your document in pdf format
pdf:
  stage: build
  image: "goffinet/gitbook:latest"
  before_script:
    - mkdir ebooks
  script:
    - 'echo "node version: $(node -v)"'
    - gitbook -V
    - calibre --version
    - gitbook install # add any requested plugins in book.json
    - gitbook pdf . ebooks/${CI_PROJECT_NAME}.goffinet.org.pdf # pdf build
  artifacts:
    paths:
      - ebooks/${CI_PROJECT_NAME}.goffinet.org.pdf
    expire_in: 1 day
  only:
    - master # this job will affect only the 'master' branch the 'pdf' job will build your document in pdf format


# the 'deploys3' job will deploy your site to your S3 bucket
deploys3:
  image: "goffinet/ansible-awscli:latest"  # We use python because there is a well-working AWS Sdk
  stage: deploy
  dependencies:
    - pdf
  script:
    - aws s3 sync ebooks s3://${BUCKET_NAME}/git --acl public-read
  environment:
    name: production
